using System;

namespace Dangl.EvaluationPackageGenerator
{
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
    // This file is automatically generated
    [System.CodeDom.Compiler.GeneratedCode("GitVersionBuild", "")]
    public static class VersionInfo
    {
        public static string Version => "0.1.22";
        public static string CommitInfo => "Branch.master.Sha.0ccf3a79642415cab4a5fd9c75f67be9418dff6a";
        public static string CommitDate => "2023-07-24";
        public static string CommitHash => "0ccf3a79642415cab4a5fd9c75f67be9418dff6a";
        public static string InformationalVersion => "0.1.22+Branch.master.Sha.0ccf3a79642415cab4a5fd9c75f67be9418dff6a";
        public static DateTime BuildDateUtc => new DateTime(2023, 9, 7, 8, 22, 27, DateTimeKind.Utc);
    }
}
