using System;

namespace Dangl.EvaluationPackageGenerator
{
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

    // This file is automatically generated
    [System.CodeDom.Compiler.GeneratedCode("GitVersionBuild", "")]
    public static class VersionInfo
    {
        public static string Version => "0.1.4";
        public static string CommitInfo => "Branch.master.Sha.2ec2d2e08c251a1a16c0c54d374491b57c0d134a";
        public static string CommitDate => "2019-01-12";
        public static string CommitHash => "2ec2d2e08c251a1a16c0c54d374491b57c0d134a";
        public static string InformationalVersion => "0.1.4+Branch.master.Sha.2ec2d2e08c251a1a16c0c54d374491b57c0d134a";
        public static DateTime BuildDateUtc => new DateTime(2019, 1, 12, 16, 17, 45, DateTimeKind.Utc);
    }
}
