using System;

namespace Dangl.EvaluationPackageGenerator
{
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
    // This file is automatically generated
    [System.CodeDom.Compiler.GeneratedCode("GitVersionBuild", "")]
    public static class VersionInfo
    {
        public static string Version => "0.1.15";
        public static string CommitInfo => "Branch.master.Sha.86858be679cacd0c8cc9309e2e3a7ed5e4fe1236";
        public static string CommitDate => "2021-08-08";
        public static string CommitHash => "86858be679cacd0c8cc9309e2e3a7ed5e4fe1236";
        public static string InformationalVersion => "0.1.15+Branch.master.Sha.86858be679cacd0c8cc9309e2e3a7ed5e4fe1236";
        public static DateTime BuildDateUtc => new DateTime(2021, 8, 8, 21, 37, 39, DateTimeKind.Utc);
    }
}